os: linux

language: java
services:
  - docker
cache: bundler
dist: bionic

install: skip

jobs:
  include:
    - name: failing
      script:
        - echo "Generating long output..."
        - for i in $(seq 1 1000); do echo "Line $i: This is a long log entry for testing purposes."; done
        - false  # force failure to trigger after_failure

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT

  

  
  

  

  
  
  

  
  
  

